version: "3.9"
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    volumes:
        - wordpress-data:/var/www/html
    networks:
      - connect
    ports:
      - 443:443
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    volumes:
        - wordpress-data:/var/www/html
    env_file:
      - .env
    networks:
      - connect
    ports:
      - 9000:9000
    restart: always
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - connect
    ports:
      - 3306:3306
    restart: always
networks:
  connect:
    name: fullstack-network
    driver: bridge
volumes:
      mariadb-data:
        name: mariadb-data
        driver_opts:
          type: none
          o: bind
          device: /home/oakerkao/data/mariadb-data/
      wordpress-data:
        name: wordpress-data
        driver_opts:
          type: none
          o: bind
          device: /home/oakerkao/data/mariadb-data/
