version: "3.8"
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    volumes:
      - /home/oakerkao/data/wordpress-data:/var/www/html
    #environment:
    networks:
      - connect
    ports:
      - 443:443
        #restart: unless-stopped
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    volumes:
      - /home/oakerkao/data/wordpress-data:/var/www/html
    environment:
      WORDPRESS_DB_NAME: wordpress_db 
      WORDPRESS_DB_USER: oussama 
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_HOST: mariadb
    networks:
      - connect
    ports:
      - 9000:9000
        #    restart: unless-stopped
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    volumes:
      - /home/oakerkao/data/mariadb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress_db 
      MYSQL_USER: oussama 
      MYSQL_PASSWORD: password 
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - connect
    ports:
      - 3306:3306
        #restart: unless-stopped

networks:
  connect:
    name: fullstack-network
    driver: bridge



      #volumes:
        #mariadb-data:
          #type: "bind"
          #o: none
          #device: /home/oakerkao/data/mariadb-data

    #wordpress-data:
